-- Hacienda can be built on hill tiles and comes sooner

UPDATE Improvements SET PrereqCivic='CIVIC_FEUDALISM' WHERE ImprovementType='IMPROVEMENT_HACIENDA';
INSERT INTO Improvement_ValidTerrains (ImprovementType, TerrainType) VALUES
	('IMPROVEMENT_HACIENDA', 'TERRAIN_PLAINS_HILLS'),
	('IMPROVEMENT_HACIENDA', 'TERRAIN_GRASS_HILLS');

-- Plantation +1 production
INSERT INTO TraitModifiers VALUES
    ('TRAIT_CIVILIZATION_EJERCITO_PATRIOTA', 'BBGV_COLUMBIA_PLANTATION_BONUS_PRODUCTION');
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
	('BBGV_COLUMBIA_PLANTATION_BONUS_PRODUCTION', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'PLOT_HAS_PLANTATION_REQUIREMENTS');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('BBGV_COLUMBIA_PLANTATION_BONUS_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
	('BBGV_COLUMBIA_PLANTATION_BONUS_PRODUCTION', 'Amount', '1');

-- Plantation +1 gold
INSERT INTO TraitModifiers VALUES
    ('TRAIT_CIVILIZATION_EJERCITO_PATRIOTA', 'BBGV_COLUMBIA_PLANTATION_BONUS_GOLD');
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
	('BBGV_COLUMBIA_PLANTATION_BONUS_GOLD', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'PLOT_HAS_PLANTATION_REQUIREMENTS');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('BBGV_COLUMBIA_PLANTATION_BONUS_GOLD', 'YieldType', 'YIELD_GOLD'),
	('BBGV_COLUMBIA_PLANTATION_BONUS_GOLD', 'Amount', '1');

-- Plantation bias upper
INSERT INTO StartBiasResources(CivilizationType, ResourceType, Tier) VALUES
    ('CIVILIZATION_GRAN_COLOMBIA', 'RESOURCE_CITRUS', 3),
    ('CIVILIZATION_GRAN_COLOMBIA', 'RESOURCE_COFFEE', 3),
    ('CIVILIZATION_GRAN_COLOMBIA', 'RESOURCE_COCOA', 3),
    ('CIVILIZATION_GRAN_COLOMBIA', 'RESOURCE_COTTON', 3),
    ('CIVILIZATION_GRAN_COLOMBIA', 'RESOURCE_DYES', 3),
    ('CIVILIZATION_GRAN_COLOMBIA', 'RESOURCE_SILK', 3),
    ('CIVILIZATION_GRAN_COLOMBIA', 'RESOURCE_SPICES', 3),
    ('CIVILIZATION_GRAN_COLOMBIA', 'RESOURCE_SUGAR', 3),
    ('CIVILIZATION_GRAN_COLOMBIA', 'RESOURCE_TEA', 3),
    ('CIVILIZATION_GRAN_COLOMBIA', 'RESOURCE_TOBACCO', 3),
    ('CIVILIZATION_GRAN_COLOMBIA', 'RESOURCE_WINE', 3),
    ('CIVILIZATION_GRAN_COLOMBIA', 'RESOURCE_INCENSE', 3),
    --('CIVILIZATION_GRAN_COLOMBIA', 'RESOURCE_OLIVES', 3),
    ('CIVILIZATION_GRAN_COLOMBIA', 'RESOURCE_BANANAS', 3);
