-- red germany prod +30% when training heavy cavalry
INSERT INTO TraitModifiers VALUES ('TRAIT_LEADER_HOLY_ROMAN_EMPEROR', 'BBGV_TRAIT_HEAVY_CAVALRY_PRODUCTION');
INSERT INTO Modifiers(ModifierId, ModifierType) VALUES ('BBGV_TRAIT_HEAVY_CAVALRY_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_TAG_ERA_PRODUCTION');
INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BBGV_TRAIT_HEAVY_CAVALRY_PRODUCTION', 'UnitPromotionClass', 'PROMOTION_CLASS_HEAVY_CAVALRY'),
    ('BBGV_TRAIT_HEAVY_CAVALRY_PRODUCTION', 'EraType', 'NO_ERA'),
    ('BBGV_TRAIT_HEAVY_CAVALRY_PRODUCTION', 'Amount', '30');