-- Nubian pitati ranged combat to 27
UPDATE Units SET RangedCombat = 27 WHERE UnitType = 'UNIT_NUBIAN_PITATI';

-- all land ranged and sea ranged unit +3 combat
INSERT INTO TraitModifiers VALUES ('TRAIT_CIVILIZATION_TA_SETI', 'BBGV_RANGED_UNIT_COMBAT_BONUS');
INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES ('BBGV_RANGED_UNIT_COMBAT_BONUS', 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY', 'REQUIREMENTS_UNIT_IS_NUBIAN_RANGED');
INSERT INTO ModifierAruguments(ModifierId, Name, Value) VALUES ('BBGV_RANGED_UNIT_COMBAT_BONUS', 'AbilityType', 'BBGV_ABILITY_NUBIA_RANGED_BONUS');
INSERT INTO UnitAbilities (UnitAbilityType, Name, Description, Inactive) VALUES ('BBGV_ABILITY_NUBIA_RANGED_BONUS', 'LOC_BBGV_ABILITY_NUBIA_RANGED_BONUS_NAME', 'LOC_BBGV_ABILITY_NUBIA_RANGED_BONUS_DESCRIPTON',  1);
INSERT INTO UnitAbilityModifiers VALUES ('BBGV_ABILITY_NUBIA_RANGED_BONUS', 'ABILITY_NUBIA_RANGED_BONUS');
INSERT INTO Modifiers(ModifierId, ModifierType) VALUES ('ABILITY_NUBIA_RANGED_BONUS', 'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH');
INSERT INTO ModifierAruguments(ModifierId, Name, Value) VALUES ('ABILITY_NUBIA_RANGED_BONUS', 'Amount', 3);

INSERT INTO RequirementSets VALUES ('REQUIREMENTS_UNIT_IS_NUBIAN_RANGED', 'REQUIREMENTSET_TEST_ANY');
INSERT INTO RequirementSetRequirement VALUES
    ('REQUIREMENTS_UNIT_IS_NUBIAN_RANGED', 'BBG_PLAYER_IS_LEADER_AMANITORE_REQUIREMENT'),
    ('REQUIREMENTS_UNIT_IS_NUBIAN_RANGED', 'REQUIREMENT_UNIT_IS_RANGED'),
    ('REQUIREMENTS_UNIT_IS_NUBIAN_RANGED', 'REQUIREMENT_UNIT_IS_NAVAL_RANGED');
INSERT INTO Requirements(RequirementId, RequirementType) VALUES ('REQUIREMENT_UNIT_IS_NAVAL_RANGED', 'REQUIREMENT_UNIT_PROMOTION_CLASS_MATCHES');
INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES ('REQUIREMENT_UNIT_IS_NAVAL_RANGED', 'UnitPromotionClass', 'PROMOTION_CLASS_NAVAL_RANGED');

    