-- crabs change to +1 production +1 gold, and may spawn on reef
DELETE FROM Resource_YieldChanges WHERE ResourceType = 'RESOURCE_CRABS';
INSERT INTO Resource_YieldChanges VALUES ('RESOURCE_CRABS', 'YIELD_GOLD', 1);
INSERT INTO Resource_YieldChanges VALUES ('RESOURCE_CRABS', 'YIELD_PRODUCTION', 1);
INSERT INTO Resource_ValidFeatures VALUES ('RESOURCE_CRABS', 'FEATURE_REEF');

-- fish boat bonus
INSERT INTO Improvement_BonusYieldChanges VALUES
    (4000, 'IMPROVEMENT_FISHING_BOATS', 'YIELD_PRODUCTION', 1, 'TECH_INDUSTRIALIZATION', NULL);

-- Pantheon: rain god
INSERT INTO Types (Type, Kind) VALUES
    ('BELIEF_BBGV_RAIN_GOD', 'KIND_BELIEF');
INSERT INTO Beliefs VALUES
    ('BELIEF_BBGV_RAIN_GOD', 'LOC_BELIEF_BBGV_RAIN_GOD_NAME', 'LOC_BELIEF_BBGV_RAIN_GOD_DESCRRIPTION', 'BELIEF_CLASS_PANTHEON');
INSERT INTO BeliefModifiers VALUES
    ('BELIEF_BBGV_RAIN_GOD', 'BBGV_ALL_CITY_HOUSING'),
    ('BELIEF_BBGV_RAIN_GOD', 'BBGV_NO_WATER_CITY_HOUSING');

INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
    ('BBGV_ALL_CITY_HOUSING', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER', 'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
    ('BBGV_ALL_CITY_HOUSING_MODIFIER', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_HOUSING', NULL);

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BBGV_ALL_CITY_HOUSING', 'ModifierId', 'BBGV_ALL_CITY_HOUSING_MODIFIER'),
    ('BBGV_ALL_CITY_HOUSING_MODIFIER', 'Amount', 1);