-- diplo no delegation or embassy favor
DELETE FROM DistrictModifiers WHERE DistrictType = 'DISTRICT_DIPLOMATIC_QUARTER' AND ModifierId = 'DIPLOMATIC_QUARTER_DELEGATION_FAVOR';
DELETE FROM DistrictModifiers WHERE DistrictType = 'DISTRICT_DIPLOMATIC_QUARTER' AND ModifierId = 'DIPLOMATIC_QUARTER_EMBASSY_FAVOR';

-- diplo +3 favor per turn
INSERT INTO DistrictModifiers(DistrictType, ModifierId) VALUES ('DISTRICT_DIPLOMATIC_QUARTER', 'BBGV_DIPLOMATIC_QUARTER_PER_TURN');
INSERT INTO Modifiers(ModifierId, ModifierType) VALUES ('BBGV_DIPLOMATIC_QUARTER_PER_TURN', 'MODIFIER_PLAYER_ADJUST_EXTRA_FAVOR_PER_TURN');
INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES ('BBGV_DIPLOMATIC_QUARTER_PER_TURN', 'Amount', 3);